uni_note/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('uni_notes.urls', namespace='uni_notes')),
    path('contact/', include('mailer.urls', namespace='contact'))
]

uni_notes/urls.py
from django.urls import path, include

# from django.conf.urls import url
from . import views

app_name = 'uni_notes'

urlpatterns = [
    # note views
    path('', views.topics_list, name='topic_list'),
    path('new_topic/', views.new_topic, name='new_topic'),
    # path(r'^new_entry/(?P<topic_id>\d+)/$',views.new_note, name='new_note'),
    # path('', views.TopicListView.as_view(), name='topic_list'),
    path('<topic>/', views.topic_content, name='topic_content'),
    path('<topic>/new_note/', views.new_note, name='new_note'),
    path('<topic>/<int:year>/<int:month>/<int:day>/<slug:note>/', views.note_detail, name='note_detail'),
    path('edit_note/<note_id>', views.edit_note, name='edit_note'),
    path('delete_note/<note_id>', views.delete_note, name="delete_note"),
    path('edit_topic/<topic_id>', views.edit_topic, name='edit_topic'),
    path('delete_topic/<topic_id>', views.delete_topic, name="delete_topic"),
    #path('contact/', views.contact, name='contact'),
]

users/urls.py
""" url for user login """


from django.urls import path, re_path
from django.contrib.auth.views import LoginView, logout_then_login

from . import views

app_name = 'users'

urlpatterns = [
    # login page
    path('login/', LoginView.as_view(template_name='users/login.html'),name="login"),
    # Logout page
    path('logout/', logout_then_login ,name="logout"),
    # Registration page
    path('register/', views.register, name='register'),
]

uni_notes/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
# 4 imports

# Custom manager
#class PublishedManager(models.Manager):
#    def get_queryset(self):
#        return super(PublishedManager, self).get_queryset()# .filter(status='published')


class Topic(models.Model):
    """ Topic that notes will go into """
    name = models.CharField(max_length=50)
    body = models.CharField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    objects = models.Manager()

    def get_absolute_url(self):
        """method for linking separate notes """
        return reverse('uni_notes:topic_content', args=[self.name])

    class Meta:
        """ order that topics will be display in """
        ordering = ("-created",)
    
    def __str__(self):
        return self.name


class Note(models.Model):
    """ Creating Post model """
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE,related_name='posted_notes')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    # Addning manager
    objects = models.Manager()
    # published = PublishedManager()

    def get_absolute_url(self):
        """ method for linking separate notes """
        return reverse('uni_notes:note_detail', args=[self.topic.name,self.publish.year,self.publish.month,self.publish.day,self.slug])

    class Meta:
        """ order that topics will be display in """
        ordering = ("-created",)

    def __str__(self):
        return self.title

uni_notes/forms.py
from cProfile import label
#from dataclasses import fields
#from email import message
from django import forms
from .models import Topic, Note

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['name', 'body',]
        labels = {'name':'Title', 'body':'Description'}
        # 428   

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'body']
        labels = {'title':'Title', 'body':'Notes'}
        

uni_notes/views.py
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.utils.text import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import get_object_or_404, render
from .models import Note, Topic
from .forms import TopicForm, NoteForm
from django.contrib.auth.decorators import login_required

# from django.views.generic import ListView


# Create your views here.
"""
def note_list(request):
    # list of all notes un-filtered 
    notes = Note.published.all()
    return render(request, 'uni_notes/note/list.html', {'notes': notes})
"""
@login_required
def note_detail(request, topic, year, month, day, note):
    """ View single post """
    topics = Topic.objects.filter(author=request.user)
    
    notes = Note.objects.filter(topic__name=topic)
    topic_name = topic
    note = get_object_or_404(Note, slug=note,
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day,
                                   topic__name=topic,
                                   )
    return render(request, 'uni_notes/note/topic_note_detail.html', {'note': note, 'topics': topics, 'notes': notes, 'topic_name': topic_name })

@login_required
def topics_list(request):
    """ list of topics + sidebar"""
    object_list = Topic.objects.filter(author=request.user)
    paginator = Paginator(object_list, 6)  # 6 post per page
    page = request.GET.get('page')
    try:
        topics = paginator.page(page)
    except PageNotAnInteger:
        # if no integer return first page
        topics = paginator.page(1)
    except EmptyPage:
        # if out of range deliver last page
        topics = paginator.page(paginator.num_pages)
     
    return render(request, 'uni_notes/note/topics.html', {'topics': topics, 'page': page, 'object_list': object_list })  # 
'''
# In future can change this to class based view
class TopicListView(ListView):
    queryset = Topic.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'uni_notes/note/topics.html'

    def get(self, request, *args, **kwargs):
'''
@login_required
def topic_content(request, topic):
    """ list of notes belonging to the topic + sidebar """
    object_list = Note.objects.filter(topic__name=topic).filter(author=request.user)
    # checking if topic belongs to owner
    topic_form_edit = Topic.objects.get(name=topic)
    
    #replace variable 'topic' as will use topic objects to produce sidebar
    topic_name = topic
    topics = Topic.objects.filter(author=request.user)
    paginator = Paginator(object_list, 6)  # 6 post per page
    page = request.GET.get('page')
    try:
        notes = paginator.page(page)
    except PageNotAnInteger:
        # if no integer return first page
        notes = paginator.page(1)
    except EmptyPage:
        # if out of range deliver last page
        notes = paginator.page(paginator.num_pages)
    return render(request, 'uni_notes/note/topic_content.html', {'notes': notes, 'topic_name': topic_name, 'topics': topics, 'page': page, 'object_list': object_list, 'topic_form_edit': topic_form_edit})


@login_required
def new_topic(request):
    """ aadding new topic """
    if request.method != 'POST':
        # create form
        form = TopicForm()
    else:
        # send data via POST
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.author = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('uni_notes:topic_list'))
    context = {'form': form}
    return render(request, 'uni_notes/note/new_topic.html', context)     

@login_required
def new_note(request, topic):
    """ aadding new note for particular topic """
    topic = Topic.objects.get(name=topic)
    if topic.author != request.user:
        raise Http404
    
    if request.method != 'POST':
        # create form
        form = NoteForm()
    else:
        # send data via POST
        form = NoteForm(request.POST)
        if form.is_valid():
            # new_post.slug = slugify(new_post.title)
            new_form = form.save(commit=False)
            new_form.author = request.user
            # form.topic = topic
            new_form.slug = slugify(new_form.title)
            new_form.topic = topic
            new_form.save()
            return HttpResponseRedirect(reverse('uni_notes:topic_content', args=[topic]))
    context = {'topic':topic,'form': form}
    return render(request, 'uni_notes/note/new_note.html', context)            

@login_required
def edit_note(request, note_id):
    """ edit note by its database id number """
    note = Note.objects.get(id=note_id)
    topic = note.topic
    if note.author != request.user:
        raise Http404
    if request.method != 'POST':
        # pre-filling form with existing data
        form = NoteForm(instance=note)
    else:
        # submit edited data
        form = NoteForm(instance=note, data=request.POST)
        if form.is_valid():
            form.save()
            # note_detail(request, topic, year, month, day, note)
            # args=[self.topic.name,self.publish.year,self.publish.month,self.publish.day,self.slug]
            return HttpResponseRedirect(reverse('uni_notes:note_detail', args=[note.topic, note.publish.year, note.publish.month, note.publish.day, note.slug]))
    context = {'note': note, 'topic': topic, 'form': form}
    return render(request, 'uni_notes/note/edit_note.html', context)


@login_required
def edit_topic(request, topic_id):
    """ edit note by its database id number """
    topic = Topic.objects.get(id=topic_id)
    
    if topic.author != request.user:
        raise Http404
    if request.method != 'POST':
        # pre-filling form with existing data
        form = TopicForm(instance=topic)
    else:
        # submit edited data
        form = TopicForm(instance=topic, data=request.POST)
        if form.is_valid():
            form.save()
            # note_detail(request, topic, year, month, day, note)
            # args=[self.topic.name,self.publish.year,self.publish.month,self.publish.day,self.slug]
            return HttpResponseRedirect(reverse('uni_notes:topic_content', args=[topic]))
    context = {'topic': topic, 'form': form}
    return render(request, 'uni_notes/note/edit_topic.html', context)

# delete topic
# Topic.objects.filter(id=1).delete()


# delete note
def delete_note(request, note_id):
    """ delete current note """
    note = Note.objects.get(id=note_id)
    topic_name = note.topic
    topic = Topic.objects.get(name=topic_name)
    Note.objects.filter(id=note_id).delete()
    return HttpResponseRedirect(reverse('uni_notes:topic_content', args=[topic]))

def delete_topic(request, topic_id):
    """ delete current topic and its notes """
    Topic.objects.filter(id=topic_id).delete()
    return HttpResponseRedirect(reverse('uni_notes:topic_list'))

uni_notes/templates/uni_notes/note/edit_note.html
{% extends 'uni_notes/base.html' %}
{% block content %}
<div class="heading">
  <h1 class="inline">Edit Note</h1>
</div>
  <form action="{% url 'uni_notes:edit_note' note.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <span></span>
      </br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>
    <button name="submit" class="btn">save changes</button>
  </form>
{% endblock content %}

uni_notes/templates/uni_notes/note/edit_topic.html
{% extends 'uni_notes/base.html' %}
{% block content %}
<div class="heading">
  <h1 class="inline">Edit Topic</h1>
</div>
  <form action="{% url 'uni_notes:edit_topic' topic.id %}" method='post'>
    {% csrf_token %}
    {{ form.as_p }}
    <span></span>
      </br></br></br></br></br></br></br></br></br></br></br></br></br></br></br>
    <button name="submit" class="btn">save changes</button>
  </form>
{% endblock content %}

uni_notes/templates/uni_notes/note/list.html
{% extends "uni_notes/base.html" %} {% block title %} All Notes {% endblock %}
{% block content %}

 <h1>My notes</h1>
 

 {% for note in notes %}
  
  <h2>
    <a href="{{ note.get_absolute_url }}"> {{ note.title }} </a>
  </h2>
  <p class="date">
     Published {{ note.publish }}
  </p>
    {{ note.body|truncatewords:10|linebreaks }}
 {% endfor %}
{% endblock %}

uni_notes/templates/uni_notes/note/new_note.html
{% extends 'uni_notes/base.html' %}
{% block content %}
<div class="heading">
  <h1 class="inline">Add new note for {{ topic }}</h1>
</div>
<div class="topic_form">
  
  <form action="{% url 'uni_notes:new_note' topic %}" method="POST" >
      {% csrf_token %}
      {{ form.as_p }}
      <span></span>
      </br></br></br></br></br></br></br></br></br></br></br></br></br>
      <button name="submit" class="btn" >add note</button>
  </form>
   
</div>  

{% endblock %}

uni_notes/templates/uni_notes/note/new_topic.html
{% extends 'uni_notes/base.html' %}
{% block content %}
<div class="heading">
  <h1 class="inline">Add new topic:</h1>
</div>
<div class="topic_form">
  
  <form action="{% url 'uni_notes:new_topic' %}" method="POST" >
      {% csrf_token %}
      {{ form.as_p }}
      <span></span>
      </br></br></br></br></br></br></br></br></br></br></br></br></br>
      <button name="submit" class="btn" >add topic</button>
  </form>
   
</div>  

{% endblock %}

uni_notes/templates/uni_notes/note/topic_content.html
{% extends "uni_notes/base.html" %} {% block title %} {{ topic_name }} {% endblock %}
{% block content %}
<div class="heading">
 <h1 class="inline">📄 Notes - {{ topic_name }}</h1>
 <a href="{% url 'uni_notes:new_note' topic_name %}" class="btn btn_position-add">+ Add Note</a>
 
</div> 
 <div class="content_space">
    
  {% if object_list|length == 0 %}
  <h2> Notes has not been added. </h2>
  {% else %}
   
  {% for note in notes %}
  <div class="description_box">
    <div class="description_box-title">
      <a href="{{ note.get_absolute_url }}" ></a>
      <p class="description_box-title-link">📄 {{ note.title|truncatechars:20 }}</p>
      
    </div>
    <div class="description_box-middle">
      <div class="description_box-middle-text">
        {{ note.body|truncatechars:50}}
      </div>
    </div>
    <div class="date description_box-bottom">
      <div class="description_box-bottom-text">
        {% if note.created != note.updated %}
           Updated {{ note.updated }}
        {% else %}
           Published {{ note.created }}  
        {% endif %}
      </div>
    </div>
  </div>

  
  {% endfor %}
  {% endif %}  
</div>  
{% include "pagination.html" with page=notes %}
<div class="btn_position-bottom block"> 
  <a href="{% url 'uni_notes:edit_topic' topic_form_edit.id %}" class="btn">📝 Edit Topic</a>
  <a href="{% url 'uni_notes:delete_topic' topic_form_edit.id %}" class="btn">🗑️ Delete Topic</a>
</div>
{% endblock %}
{% block sidebar %}

  {% for topic in topics %}
      <div class="btn_topic">
        <a href="{{ topic.get_absolute_url }}">{{ topic.name }}</a>
      </div>  
      {% if topic.name == topic_name %}
          {% for note in object_list %}
              <a href="{{ note.get_absolute_url }}" class="btn_topic__notes">{{ note.title|truncatechars:16 }}</a>
          {% endfor %}
      {% endif %}
  {% endfor %}
{% endblock  %}    
    

uni_notes/templates/uni_notes/note/topic_note_detail.html
{% extends 'uni_notes/base.html' %}

{% block title %} {{ note.title }} {% endblock %}

{% block content %}
<div class="heading">
  <h1 class="inline">📄 {{ note.topic }} - {{ note.title }}</h1>
  
</div>
  <p class="date">
      Published {{ note.publish }}
  </p>
  <p class="date">
      Updated {{ note.updated }}
  </p>
   {{ note.body|linebreaks }}
   <div class="btn_position-bottom block"> 
    <a href="{% url 'uni_notes:edit_note' note.id %}" class ="btn">📄 Edit note</a>
   <a href="{% url 'uni_notes:delete_note' note.id %}" class="btn">🗑️ Delete note</a>
  </div>
   
{% endblock  %}
{% block sidebar %}
  {% for topic in topics %}
      <div class="btn_topic">
        <a href="{{ topic.get_absolute_url }}">{{ topic.name }}</a>
      </div>  
        {% if topic.name == topic_name %}
          {% for note in notes %}
            <a href="{{ note.get_absolute_url }}" class="btn_topic__notes">{{ note.title|truncatechars:16 }}</a>
          {% endfor %}
        {% endif %}
  {% endfor %}
{% endblock  %}

uni_notes/templates/uni_notes/note/topics.html
{% extends "uni_notes/base.html" %} {% block title %} All Topics {% endblock %}
{% block content %}
<div class="heading">
  <h1 class="inline">📰 Topics</h1>
  
</div>
  <div class="content_space"> 
 {% for topic in topics %}
  
 
  <div class="description_box">
    <div class="description_box-title">
      <a href="{{ topic.get_absolute_url }}"></a>
      <p class="description_box-title-link">📰 {{ topic.name|truncatechars:22 }}</p>
      
    </div>
    <div class="description_box-middle">
      <div class="description_box-middle-text">
        {{ topic.body|truncatechars:50 }}
      </div>
    </div>
    <div class="date description_box-bottom">
      <div class="description_box-bottom-text">
        
        {% if topic.created != topic.updated %}
           Updated {{ topic.updated }}
        {% else %}
           Published {{ topic.created }}  
        {% endif %}
      </div>
    </div>
  </div>
    
 {% endfor %}
</div>
 {% include "pagination.html" with page=topics %}
 <a href="{% url 'uni_notes:new_topic' %}" class ="btn btn_position-add">+ Add Topic</a>
{% endblock %}
{% block sidebar %}

{% for topic in object_list %}
  <div class="btn_topic">
    <a href="{{ topic.get_absolute_url }}"> {{ topic.name }} </a>
  </div>
 
{% endfor %}

{% endblock  %}